# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "0e839a831948915c25542d1cf0323533"
name = "AutoNotify - Restock Alert"
application_url = "https://autonotify-restock-alert.up.railway.app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_inventory,read_themes,write_products"



  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/customers/data_request"
  compliance_topics = [ "customers/data_request" ]
 
  [[webhooks.subscriptions]]
  uri = "/webhooks/app/customers/redact"
  compliance_topics = [ "customers/redact" ]
 
  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  compliance_topics = [ "shop/redact" ]

[auth]
redirect_urls = [
  "https://autonotify-restock-alert.up.railway.app/auth/callback",
  "https://autonotify-restock-alert.up.railway.app/auth/shopify/callback",
  "https://autonotify-restock-alert.up.railway.app/api/auth/callback"
]
