# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a36304472c3c12ef411efd76f8ce2728"
name = "Notify Me"
application_url = "https://indication-languages-resist-luke.trycloudflare.com"
embedded = true
handle = "notify-me-46"

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_inventory,write_products,read_themes"

[auth]
redirect_urls = [
  "https://indication-languages-resist-luke.trycloudflare.com/auth/callback",
  "https://indication-languages-resist-luke.trycloudflare.com/auth/shopify/callback",
  "https://indication-languages-resist-luke.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
