# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "edee2764bd0aaa841ef0ab2250ff22f7"
name = "AutoNotify - Restock Alert"
application_url = "https://example.com"
embedded = true

[webhooks]
api_version = "2025-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_inventory,write_products,read_themes"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]
